summer-white:
	python3 lab1.py terrain.png mpp.txt normal/white.txt summer output.png

summer-brown:
	python3 lab1.py terrain.png mpp.txt normal/brown.txt summer output.png

summer-red:
	python3 lab1.py terrain.png mpp.txt normal/red.txt summer output.png

winter-white:
	python3 lab1.py terrain.png mpp.txt normal/white.txt winter output.png
winter-brown:
	python3 lab1.py terrain.png mpp.txt normal/brown.txt winter output.png
winter-red:
	python3 lab1.py terrain.png mpp.txt normal/red.txt winter output.png
spring-white:
	python3 lab1.py terrain.png mpp.txt normal/white.txt spring output.png
spring-brown:
	python3 lab1.py terrain.png mpp.txt normal/brown.txt spring output.png
spring-red:
	python3 lab1.py terrain.png mpp.txt normal/red.txt spring output.png
fall-white:
	python3 lab1.py terrain.png mpp.txt normal/white.txt fall output.png
fall-brown:
	python3 lab1.py terrain.png mpp.txt normal/brown.txt fall output.png
fall-red:
	python3 lab1.py terrain.png mpp.txt normal/red.txt fall output.png

